### ISSUE TITLE
Add Code Coverage Reporting

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#431]
For each repo we need to:
- update the `travis.yml` file
  
  ```
  sudo: false
  language: node_js
  node_js:
    - 'node'
    - '6'
    - '4'
    - 'iojs' #end of life Jan. 2017
    - '0.12' #end of life Jan. 2017
    - '0.10' #end of life Jan. 2017
  addons:
    code_climate:
      repo_token: 'd91570a5de532850a5c512e5f5f33a459060b8f38d7ab15487e1eb219e2577ee'
  before_script:
    - npm install -g codeclimate-test-reporter
  after_script:
    - codeclimate-test-reporter < coverage/lcov.info
  ```
- add a `.istanbul.yml` file
  
  ```
  verbose: false
  instrumentation:
    root: src/
    excludes:
      - lib/
    include-all-sources: true
  reporting:
    print: summary
    reports:
      - html
      - text
      - lcov
    watermarks:
      statements: [50, 80]
      lines: [50, 80]
      functions: [50, 80]
      branches: [50, 80]
  ```
- update the `.gitignore` and `.npmignore files`
- add a `mocha.opts` file
  
  ```
  --recursive test/
  --compilers js:babel-core/register
  ```
- add build badges to readme
- update `package.json` file
  - add a `coverage` task (see complete repos)

`"coverage": "istanbul cover node_modules/mocha/bin/_mocha -- --opts mocha.opts",`

```
- update mocha task to use `mocha.opts`
- update `test` task to use `npm run coverage` instead of `npm run mocha`
- install istanbul
```
- ensure the repo is added to CodeClimate

You can find the `repo_token` by going into "settings" and then "test coverage".

![screen shot 2016-10-21 at 11 21 03 pm](https://cloud.githubusercontent.com/assets/599019/19617131/5b960c2e-97e5-11e6-8782-a76c6fcccc67.png)

![screen shot 2016-10-21 at 11 21 15 pm](https://cloud.githubusercontent.com/assets/599019/19617132/5d0ceae6-97e5-11e6-8010-1b5a05f90fd0.png)
- Add badges / changelog to Ecosystem page
  https://github.com/feathersjs/feathers-docs/blob/ecosystem/why/ecosystem.md
### Repos
- [ ] generator-feathers-plugin
- [ ] feathers-service-tests?
- [x] feathers-hooks-common
- [x] feathers-authentication-local
- [x] feathers-authentication
- [x] feathers-authentication-oauth2
- [x] feathers-authentication-client
- [x] feathers-knex
- [x] feathers-localstorage
- [x] feathers-errors
- [x] feathers-sendgrid
- [x] feathers-mailgun
- [x] feathers-mailer
- [x] feathers-stripe
- [x] feathers-twilio
- [x] feathers-blob
- [x] feathers-levelup
- [x] feathers-cli
- [x] feathers-generator
- [x] feathers-sequelize
- [x] feathers-reactive
- [x] feathers-waterline
- [x] feathers-configuration
- [x] feathers-batch
- [x] feathers-sync
- [x] feathers-bootstrap
### Require updates to coverage task to use relative path to _mocha

`"coverage": "istanbul cover node_modules/mocha/bin/_mocha -- --opts mocha.opts",`
- [x] feathers
- [x] feathers-permissions
- [x] feathers-mongodb
- [x] feathers-mongoose
- [x] feathers-nedb
- [x] feathers-query-filters
- [x] feathers-hooks
- [x] feathers-commons
- [x] feathers-rethinkdb
- [x] feathers-socket-commons
- [x] feathers-primus
- [x] feathers-socketio
- [x] feathers-rest **-> PR [#78](https://github.com/feathersjs/feathers-rest/pull/78)**
- [x] feathers-memory
